#!/usr/bin/env python3
"""Does selectivity really decline in the later part of the introspection SFT?

Written to be run UNATTENDED and to reach a verdict without a human in the loop, so it
states its criteria first and then applies them.

The hazard is specific and was already met once in this work: on the sparse curve, a peak
at 0.76 epochs and a dip at 1.00 had disjoint question-bootstrap intervals and looked real.
Four extra checkpoints showed adjacent ones (15 optimizer steps apart) move B1 by up to
0.446. The interval was measuring variance over evaluation questions, which is not the
variance that matters here. So this script judges the trend against CHECKPOINT SCATTER,
estimated from the residuals of its own fit, not against a question bootstrap.

Two questions, kept apart:

  1. TREND. Fit selectivity ~ a + b*epoch over the points at one epoch and beyond. Report b
     with a standard error built from the residual scatter. A decline counts only if the
     slope is more than 2 standard errors below zero.

  2. CONFOUND. Selectivity falls while dose rises, so "later training" and "more
     displacement" are not separated by the trend alone. For each late checkpoint, look up
     M_D's selectivity at the SAME measured dose and take the difference. If the excess over
     M_D also declines, the effect is not merely displacement. Interpolation is refused
     outside M_D's measured range; where the ladder does not reach, the row says so rather
     than extrapolating.
"""
from __future__ import annotations

import argparse
import csv
import statistics as st
import sys
from pathlib import Path

import numpy as np

REPO = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO / "scripts" / "appendix_oct"))
import curve_common as cc  # noqa: E402

MASTER = REPO / "outputs" / "analysis" / "oct_stage_dose_master.csv"
SLOPE_SE_THRESHOLD = 2.0


def md_ladder(rows):
    """(dose, selectivity) for M_D, from the dose-matched rungs plus any new ones."""
    pts = []
    for r in rows:
        if r["kind"] == "reference" and r["state"] == "M_D" and r["dose"] and r.get("selectivity"):
            pts.append((r["dose"], r["selectivity"]))
    if MASTER.exists():
        with open(MASTER) as fh:
            for r in csv.DictReader(fh):
                if r["state"] == "M_D" and r["row_source"] == "extraction" and r["dose"] and r.get("selectivity"):
                    pts.append((float(r["dose"]), float(r["selectivity"])))
    seen, out = set(), []
    for d, s in sorted(pts):
        if round(d, 4) not in seen:
            seen.add(round(d, 4)); out.append((d, s))
    return out


def fit(x, y):
    x = np.asarray(x, float); y = np.asarray(y, float)
    b, a = np.polyfit(x, y, 1)
    resid = y - (a + b * x)
    n = len(x)
    if n <= 2:
        return b, a, float("nan"), float("nan")
    s_resid = float(np.sqrt((resid ** 2).sum() / (n - 2)))
    se_b = s_resid / float(np.sqrt(((x - x.mean()) ** 2).sum()))
    return float(b), float(a), s_resid, float(se_b)


def main() -> None:
    p = argparse.ArgumentParser()
    p.add_argument("--out", required=True)
    p.add_argument("--construction", default="seq")
    a = p.parse_args()

    rows = cc.load()
    pts = sorted([r for r in rows if r["kind"] == "curve" and r["construction"] == a.construction
                  and r.get("selectivity") is not None and r.get("dose") is not None],
                 key=lambda r: r["step"])
    late = [r for r in pts if r["epoch"] >= 1.0]
    early = [r for r in pts if 0.60 <= r["epoch"] <= 0.95]

    L = ["# Is the late-SFT selectivity decline real?", "",
         "Generated by `scripts/appendix_oct/curve_late_stats.py`, run unattended. Criteria were",
         "fixed in that script before these numbers existed; it judges the trend against",
         "**checkpoint scatter**, not against a question bootstrap — the distinction that",
         "retired the apparent overshoot in [SFT_CURVE_REPORT.md](SFT_CURVE_REPORT.md).", ""]

    if len(late) < 4:
        L += [f"**Inconclusive: only {len(late)} checkpoints at or past one epoch.** "
              "The measurement did not complete far enough to fit a trend.", ""]
        Path(a.out).write_text("\n".join(L) + "\n")
        print(f"wrote {a.out} (inconclusive, {len(late)} late points)")
        return

    b, a0, s_resid, se_b = fit([r["epoch"] for r in late], [r["selectivity"] for r in late])
    z = b / se_b if se_b and se_b == se_b else float("nan")
    declines = (z < -SLOPE_SE_THRESHOLD)

    L += ["## 1. Trend over one epoch and beyond", "",
          f"- checkpoints used: **{len(late)}** ({late[0]['epoch']:.2f} to {late[-1]['epoch']:.2f} epochs)",
          f"- slope: **{b:+.4f}** selectivity per epoch  (SE {se_b:.4f}, {z:+.1f} SE from zero)",
          f"- residual scatter between checkpoints: **{s_resid:.4f}**",
          "", f"**Verdict: {'a real decline' if declines else 'NOT established'}** "
          f"— the criterion was a slope more than {SLOPE_SE_THRESHOLD:.0f} SE below zero.", ""]
    if early:
        L += [f"For scale, checkpoints between {early[0]['epoch']:.2f} and {early[-1]['epoch']:.2f} epochs "
              f"have selectivity mean {st.mean(r['selectivity'] for r in early):.3f}"
              + (f", sd {st.stdev(r['selectivity'] for r in early):.3f}" if len(early) > 1 else "") + ".", ""]

    L += ["| epoch | step | dose | selectivity | $B_1$ |", "|---|---|---|---|---|"]
    for r in late:
        L.append(f"| {r['epoch']:.2f} | {r['step']} | {r['dose']:.3f} | {r['selectivity']:.3f} | {r['B1']:+.3f} |")
    L.append("")

    # 2. dose control
    lad = md_ladder(rows)
    L += ["## 2. Is it training time, or just displacement?", ""]
    if len(lad) < 2:
        L += ["No usable M_D selectivity ladder; the dose control cannot be run.", ""]
    else:
        ld = np.array([p[0] for p in lad]); ls = np.array([p[1] for p in lad])
        L += [f"M_D's selectivity ladder spans dose **{ld.min():.3f}–{ld.max():.3f}** "
              f"({len(lad)} rungs). Excess is the checkpoint's selectivity minus M_D's at the "
              "same measured dose; nothing is extrapolated.", "",
              "| epoch | dose | curve sel. | $M_D$ sel. at that dose | excess |", "|---|---|---|---|---|"]
        ex_x, ex_y = [], []
        for r in late:
            if ld.min() <= r["dose"] <= ld.max():
                m = float(np.interp(r["dose"], ld, ls))
                L.append(f"| {r['epoch']:.2f} | {r['dose']:.3f} | {r['selectivity']:.3f} | {m:.3f} | {r['selectivity']-m:+.3f} |")
                ex_x.append(r["epoch"]); ex_y.append(r["selectivity"] - m)
            else:
                L.append(f"| {r['epoch']:.2f} | {r['dose']:.3f} | {r['selectivity']:.3f} | "
                         f"— *outside the ladder* | — |")
        L.append("")
        if len(ex_x) >= 4:
            eb, _, es, ese = fit(ex_x, ex_y)
            ez = eb / ese if ese and ese == ese else float("nan")
            L += [f"Excess-over-$M_D$ slope: **{eb:+.4f}** per epoch (SE {ese:.4f}, {ez:+.1f} SE), "
                  f"residual scatter {es:.4f}.", "",
                  f"**{'The decline survives the dose control' if ez < -SLOPE_SE_THRESHOLD else 'The decline does NOT survive the dose control'}**"
                  " — so the loss of specificity "
                  + ("is not explained by the model simply moving further." if ez < -SLOPE_SE_THRESHOLD
                     else "cannot be separated from displacement on this evidence."), ""]
        else:
            L += [f"Only {len(ex_x)} late checkpoints fall inside M_D's measured dose range, "
                  "which is too few to fit the control. The M_D ladder needs extending further.", ""]

    L += ["## Limits", "",
          "- One seed, one trait, one model, one construction "
          f"(`{a.construction}`).",
          "- Checkpoint scatter is estimated from the residuals of this fit, so it assumes the",
          "  underlying trend really is close to linear over this range.",
          "- Question-bootstrap intervals are deliberately not used here; they answer a",
          "  different question and were misleading earlier in this work.", ""]

    Path(a.out).write_text("\n".join(L) + "\n")
    print(f"wrote {a.out}: slope {b:+.4f} ({z:+.1f} SE), declines={declines}")


if __name__ == "__main__":
    main()
