#!/usr/bin/env python3
"""Appendix asset 1 -- what the OCT stages and our constructions actually are.

Scientific question: which model states are being compared, and how is each built? A reader
meeting M_D / M_D+S / M_F / M_S for the first time needs this before any result.

THE ONE THING THIS FIGURE MUST NOT LET A READER MISBELIEVE: that M_S is DPO-free. Its
WEIGHTS start from the base model, but the corpus it trains on was GENERATED by the DPO
model. DPO is removed from the optimisation, never from the causal history. The corpus box
therefore sits between M_D and BOTH SFT branches, and the annotation under M_S says so.

Layout is an explicit 5-row x 3-column grid with hand-checked, non-overlapping extents --
matplotlib will not reflow boxes to avoid collisions, so the coordinates are the design.
Edge labels sit BESIDE their arrows, never on them.

Regenerate:  python scripts/appendix_oct/figA_oct_stage_pipeline.py
"""
from __future__ import annotations

import sys
from pathlib import Path

import matplotlib.pyplot as plt
from matplotlib.patches import FancyArrowPatch, FancyBboxPatch

REPO = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO / "workshop_iclr" / "scripts"))
from figstyle import INK, MUTED, use_style                    # noqa: E402

OUT = REPO / "iclr2026" / "figures"
BLUE, LBLUE, ORANGE, PINK, BLACK = "#2a78d6", "#5aa9e6", "#eb6834", "#b5179e", "#111111"
CORPUS = "#5c6b6c"

# rows (y of box bottom) and a uniform box height
R = {"base": 0.875, "dpo": 0.700, "corpus": 0.525, "sft": 0.290, "merge": 0.075}
HB = 0.098


def box(ax, cx, y, w, text, ec, fc="white", fs=6.9, ls="-", lw=1.15):
    ax.add_patch(FancyBboxPatch((cx - w / 2, y), w, HB,
                                boxstyle="round,pad=0.008,rounding_size=0.018",
                                linewidth=lw, edgecolor=ec, facecolor=fc, linestyle=ls,
                                zorder=3))
    ax.text(cx, y + HB / 2, text, ha="center", va="center", fontsize=fs, color=INK,
            zorder=4, linespacing=1.3)


def arrow(ax, p, q, color=INK, ls="-", lw=1.0):
    ax.add_patch(FancyArrowPatch(p, q, arrowstyle="-|>", mutation_scale=7.5, linewidth=lw,
                                 color=color, linestyle=ls, shrinkA=1, shrinkB=1, zorder=2))


def main() -> None:
    use_style()
    fig, ax = plt.subplots(figsize=(5.5, 4.3))
    ax.set_xlim(0, 1); ax.set_ylim(-0.02, 1.0); ax.axis("off")

    CL, CC, CR = 0.155, 0.500, 0.845          # column centres

    box(ax, CC, R["base"],   0.30, r"$M_0$   base model", MUTED)
    box(ax, CC, R["dpo"],    0.30, r"$M_D$   DPO update only", BLUE, lw=1.4)
    box(ax, CC, R["corpus"], 0.42,
        r"$\mathcal{D}_{\mathrm{int}}$  introspection corpus," "\n"
        r"generated $by$ $M_D$", CORPUS, fc="#f1f4f4")
    box(ax, CR, R["sft"],    0.29, r"$M_{D+S}$" "\nSFT on folded DPO state", ORANGE, lw=1.4, fs=6.3)
    box(ax, CL, R["sft"],    0.29, r"$M_S$" "\nSFT from $M_0$", PINK, lw=1.4)
    # bottom row sits on its own, tighter centres so the wider boxes stay inside the axes
    BL, BR = 0.175, 0.825
    box(ax, BR, R["merge"],  0.30, r"$M_F$" "\n" r"PEFT merge, $with$ cross terms",
        BLACK, lw=1.4, fs=6.0)
    box(ax, BL, R["merge"],  0.30, r"$M_{D+0.25S}$" "\n" r"additive, $no$ cross terms",
        LBLUE, ls=(0, (3, 2)), fs=6.0)

    # vertical spine, labels beside the arrows
    arrow(ax, (CC, R["base"]), (CC, R["dpo"] + HB), MUTED)
    ax.text(CC + 0.018, (R["base"] + R["dpo"] + HB) / 2, "DPO", fontsize=6.5, color=MUTED,
            ha="left", va="center")
    arrow(ax, (CC, R["dpo"]), (CC, R["corpus"] + HB), CORPUS)
    ax.text(CC + 0.018, (R["dpo"] + R["corpus"] + HB) / 2, "generates", fontsize=6.5,
            color=CORPUS, ha="left", va="center")

    # corpus feeds BOTH branches -- this is the causal point
    arrow(ax, (CC + 0.16, R["corpus"] + 0.02), (CR - 0.02, R["sft"] + HB), ORANGE)
    arrow(ax, (CC - 0.16, R["corpus"] + 0.02), (CL + 0.02, R["sft"] + HB), PINK)
    # the DPO WEIGHTS also feed the native branch (dashed = weights, solid = data)
    arrow(ax, (CC + 0.15, R["dpo"] + 0.02), (CR - 0.03, R["sft"] + HB - 0.005), BLUE,
          ls=(0, (3, 2)))
    arrow(ax, (CC - 0.15, R["base"] + 0.02), (CL - 0.02, R["sft"] + HB), MUTED, ls=(0, (3, 2)))

    arrow(ax, (CR, R["sft"]), (BR, R["merge"] + HB), BLACK)

    ax.annotate("", xy=(BR - 0.157, R["merge"] + HB / 2), xytext=(BL + 0.157, R["merge"] + HB / 2),
                arrowprops=dict(arrowstyle="<->", color=MUTED, lw=0.9, shrinkA=1, shrinkB=1))
    ax.text((CL + CR) / 2, R["merge"] + HB / 2 + 0.016, "same components", ha="center",
            va="bottom", fontsize=6.2, color=MUTED)

    ax.text(CL, R["sft"] - 0.022, "weights start at $M_0$;\ncorpus still comes from $M_D$",
            ha="center", va="top", fontsize=6.2, color=PINK, linespacing=1.3)
    ax.text(0.5, 0.012, "solid = data flow        dashed = weight initialisation",
            ha="center", va="bottom", fontsize=6.2, color=MUTED)

    OUT.mkdir(parents=True, exist_ok=True)
    for ext in ("pdf", "png"):
        fig.savefig(OUT / f"figA_oct_stage_pipeline.{ext}")
    print(f"  wrote {OUT}/figA_oct_stage_pipeline.pdf/.png")


if __name__ == "__main__":
    main()
